### ISSUE TITLE
Some trivial questions 

### ISSUE THREAD

**Issue by gyeongjin-kim** [viswavi/few-shot-clustering#4]
The 2nd and 3rd examples in READEME.md provide the same Utterance#2. Is this intentional?
Furthermore, shouldn't the answer in the 3rd example be No, not Yes?

```
Utterance #1: how soon milk expires
Utterance #2: can you roll an eight sided die and tell me what it comes up as

Given this context, do utterance #1 and utterance #2 likely express the same general intent? Yes
```

---

As far as GPT 4O MINI is concerned, will this be reflected in future GPT versions so that we can customize them?

**Comment by viswavi** [comment]
Hi @kj4483 , I'm sorry for the terribly late response! Th issue in the README that you pointed out was indeed an error in the README, which i have fixed!

Regarding gpt-4o mini, you can simply replace "gpt-3.5-turbo" with "gpt-4o" in these places here
https://github.com/search?q=repo%3Aviswavi%2Factive_semi_supervised_clustering%20openai&type=code

I have created #5 to properly address this. Stay tuned for that
